package net.benjaminurquhart.legible;

public enum MovementCommand {
	ROUTE_END,
	ROUTE_MOVE_DOWN,
	ROUTE_MOVE_LEFT,
	ROUTE_MOVE_RIGHT,
	ROUTE_MOVE_UP,
	ROUTE_MOVE_LOWER_L,
	ROUTE_MOVE_LOWER_R,
	ROUTE_MOVE_UPPER_L,
	ROUTE_MOVE_UPPER_R,
	ROUTE_MOVE_RANDOM,
	ROUTE_MOVE_TOWARD,
	ROUTE_MOVE_AWAY,
	ROUTE_MOVE_FORWARD,
	ROUTE_MOVE_BACKWARD,
	ROUTE_JUMP,
	ROUTE_WAIT,
	ROUTE_TURN_DOWN,
	ROUTE_TURN_LEFT,
	ROUTE_TURN_RIGHT,
	ROUTE_TURN_UP,
	ROUTE_TURN_90D_R,
	ROUTE_TURN_90D_L,
	ROUTE_TURN_180D,
	ROUTE_TURN_90D_R_L,
	ROUTE_TURN_RANDOM,
	ROUTE_TURN_TOWARD,
	ROUTE_TURN_AWAY,
	ROUTE_SWITCH_ON,
	ROUTE_SWITCH_OFF,
	ROUTE_CHANGE_SPEED,
	ROUTE_CHANGE_FREQ,
	ROUTE_WALK_ANIME_ON,
	ROUTE_WALK_ANIME_OFF,
	ROUTE_STEP_ANIME_ON,
	ROUTE_STEP_ANIME_OFF,
	ROUTE_DIR_FIX_ON,
	ROUTE_DIR_FIX_OFF,
	ROUTE_THROUGH_ON("Through ON"),
	ROUTE_THROUGH_OFF("Through OFF"),
	ROUTE_TRANSPARENT_ON("Transparent ON"),
	ROUTE_TRANSPARENT_OFF("Transparent OFF"),
	ROUTE_CHANGE_IMAGE,
	ROUTE_CHANGE_OPACITY,
	ROUTE_CHANGE_BLEND_MODE,
	ROUTE_PLAY_SE("Play Sound"),
	ROUTE_SCRIPT;
	
	private final String name;
	
	private MovementCommand() {
		this.name = name();
	}
	
	private MovementCommand(String name) {
		this.name = name;
	}
	
	@Override
	public String toString() {
		return name;
	}
}
